cmake_minimum_required(VERSION 4.3)
project(uni_labs C)

set(CMAKE_C_STANDARD 11)

add_executable(uni_labs main.c)

add_executable(cw_main lab1/classwork/main.c)
add_executable(cw_main2 lab2/classwork/main.c)
add_executable(task_2_7 lab2/classwork/task_2.7.c)
add_executable(task_2_6 lab2/classwork/task_2.6.c)
add_executable(task_2_5 lab2/classwork/task_2.5.c)
add_executable(task_2_4 lab2/classwork/task_2.4.c)
add_executable(task_2_3 lab2/classwork/task_2.3.c)
add_executable (task_2_2 lab2/classwork/task_2.2.c)
add_executable(hw_main2 lab2/homework/main.c)
add_executable(task_2_17 lab2/homework/task_2.17.c)
add_executable(task_2_8 lab2/homework/task_2.8.c)
add_executable(task_2_1 lab2/classwork/task_2.1.c)

add_executable(task_1_9 lab1/classwork/task_1.9.c)
add_executable(task_1_8 lab1/classwork/task_1.8.c)
add_executable(task_1_7 lab1/classwork/task_1.7.c)
add_executable(task_1_6 lab1/classwork/task_1.6.c)
add_executable(task_1_5 lab1/classwork/task_1.5.c)
add_executable(task_1_3 lab1/classwork/task_1.3.c)
add_executable(task_1_2 lab1/classwork/task_1.2.c)

add_executable(hw_main lab1/homework/main.c)
add_executable(task_1_17 lab1/homework/task_1.17.c)
add_executable(task_1_11 lab1/homework/task_1.11.c)

add_executable(task_1_1 lab1/classwork/task_1.1.c)
add_executable(task_1_4 lab1/classwork/task_1.4.c)

